version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - ./backend/.env
    ports:
      - "5555:3000"
    volumes:
      - ./dist:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "node --watch main.js"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stefashka1207
    env_file:
      -  .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5434:5432"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
